import PushNotification from 'react-native-push-notification';
import PushNotificationIOS from '@react-native-community/push-notification-ios';
import { Platform } from 'react-native';

const CHANNEL_ID = 'giftu-channel-id';
const CHANNEL_NAME = 'Giftu Notifications';
const CHANNEL_DESCRIPTION = 'Channel for Giftu app notifications';

class NotificationService {
  configure = (onNotification) => {
    PushNotification.configure({
      onRegister: function (token) {
        console.log('NOTIFICATION TOKEN:', token);
      },
      onNotification: function (notification) {
        console.log('RECEIVED NOTIFICATION:', notification);
        if (Platform.OS === 'ios') {
          if (notification.data.openedInForeground) {
            // For iOS, if app is in foreground, present the notification.
            // This is often handled by default or in willPresentNotification in AppDelegate
            // but can be explicitly done if needed.
            // notification.finish(PushNotificationIOS.FetchResult.NoData); // Call finish if needed
            console.log('iOS foreground notification:', notification);
          }
        }
        // Callback to handle notification press, etc.
        if (onNotification && typeof onNotification === 'function') {
          onNotification(notification);
        }
        // Required on iOS only (even for local notifications)
        // Needs to be called if you are handling the notification in JS and not natively
        if (Platform.OS === 'ios') {
            notification.finish(PushNotificationIOS.FetchResult.NoData);
        }
      },
      onAction: function (notification) {
        console.log('ACTION:', notification.action);
        console.log('NOTIFICATION WHEN ACTION:', notification);
        // process the action
      },
      onRegistrationError: function (err) {
        console.error('Notification registration error:', err.message, err);
      },
      // IOS ONLY (optional): default: all - Permissions to register.
      permissions: {
        alert: true,
        badge: true,
        sound: true,
      },
      popInitialNotification: true,
      requestPermissions: Platform.OS === 'ios', // Request permissions on iOS automatically
    });

    this.createDefaultChannels();
  };

  createDefaultChannels = () => {
    if (Platform.OS === 'android') {
      PushNotification.createChannel(
        {
          channelId: CHANNEL_ID, // (required)
          channelName: CHANNEL_NAME, // (required)
          channelDescription: CHANNEL_DESCRIPTION, // (optional) default: undefined.
          soundName: 'default', // (optional) See `soundName` parameter of `localNotification` function
          importance: 4, // (optional) default: 4. Int value of the Android notification importance (PendingIntent)
          vibrate: true, // (optional) default: true. Creates the default vibration pattern if true.
        },
        (created) =>
          console.log(`createChannel '${CHANNEL_ID}' returned '${created}'`), // (optional) callback returns whether the channel was created, false means it already existed.
      );
    }
  };

  requestPermissions = () => {
    if (Platform.OS === 'ios') {
      return PushNotificationIOS.requestPermissions();
    }
    // Android permissions are implicitly granted for notifications usually,
    // unless specific types of notifications or behaviors are needed.
    // For local notifications, channel setup is the main thing.
    return Promise.resolve(true); 
  }

  // id should be a string
  scheduleNotification = (id, title, message, date, userInfo = {}) => {
    if (!date || !(date instanceof Date) || isNaN(date.getTime())) {
        console.error("Invalid date provided for scheduling notification:", date);
        return;
    }
    console.log(`Scheduling notification id: ${id}, title: ${title}, date: ${date}`);

    PushNotification.localNotificationSchedule({
      /* Android Only Properties */
      channelId: CHANNEL_ID, // (required) channelId, if the channel doesn't exist, notification will not trigger.
      // largeIcon: "ic_launcher", // (optional) default: "ic_launcher". Use "" for no large icon.
      // smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher". Use "" for default small icon.
      
      /* iOS and Android properties */
      id: id, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
      title: title, // (optional)
      message: message, // (required)
      date: date, // Date object
      userInfo: { ...userInfo, id: id }, // pass info, ensure id is part of it
      playSound: true,
      soundName: 'default',
      allowWhileIdle: true, // Allow notification to trigger in doze mode
      // repeatType: 'day', // Example: 'month', 'week', 'day', 'hour', 'minute'
    });
  };

  cancelNotification = (id) => {
    console.log(`Cancelling notification id: ${id}`);
    PushNotification.cancelLocalNotification(id); // id needs to be a string
  };

  cancelAllNotifications = () => {
    PushNotification.cancelAllLocalNotifications();
  }
}

export default new NotificationService();
